services:
  cats-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CATS_API_BASE_URL=${CATS_API_BASE_URL}
      - CATS_API_KEY=${CATS_API_KEY}
    networks:
      - cats-network

networks:
  cats-network:
    driver: bridge